# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg Williams
email: greg@vgdub.com
description: > # this means to ignore newlines until "baseurl:"
  I'm currently looking for remote & full-time work in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_assets_images: "assets/images"
url: "http://vgdub.com" # the base hostname & protocol for your site
twitter_username: vgdub
github_username:  vgdub
instagram_username: vgdub

# Build settings
markdown: kramdown
